### ISSUE TITLE
Error after updating to R version 3.3.2

### ISSUE THREAD

**Issue by martinbruckner** [brendan-r/boxr#50]
After updating to R version 3.3.2, I get the following error message, when trying to authenticate:

> box_auth()
Reading client id from .Renviron
Reading client secret from .Renviron
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failure when receiving data from the peer

**Comment by brendan-r** [comment]
Hey @martinbruckner ,

I'm using R 3.3.2; this is not the cause.

The errors do not come from `boxr` but from the `httr`/`curl` packages, upon which boxr depends. Reinstalling them is probably a good start. Other than that, I suggest you look for help with those packages (e.g. perform a web search for the error message(s)).

Sorry I can't be more help!

**Comment by james-matthiesen** [comment]
Hello. Was a solution ever found to this problem? I am experiencing the exact same issue and exact same error message. 

 *> box_auth()
Reading client id from .Renviron
Reading client secret from .Renviron
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failure when receiving data from the peer*

The only thing that has changed since I my last successful use of this package was the R update. I'm afraid I'm still very much an R novice. I understand that the error has to do with the token2.0 creation, but I have difficulty understanding how to investigate the curl error. The internet suggests that it has to do with the certificate my computer is using but this error message in particular has not been getting a lot of love on Stack Overflow, and I'm just about at my wit's end.
@martinbruckner 
Did you have any success fixing this error?

**Comment by martinbruckner** [comment]
I have reinstalled the httr and curl packages, but without success.

**Comment by james-matthiesen** [comment]
That mirrors my process too. Thank you for the response. I'll keep looking.

**Comment by brendan-r** [comment]
I would raise this error on the GH issues page for the `curl` package.

You could also try resetting your local token (will require re-authorizing your app, e.g. clicking 'OK' in a browser), buy running `box_fresh_auth`.

**Comment by james-matthiesen** [comment]
Thank you, I appreciate the help.
