### ISSUE TITLE
Feature suggestion: pass parser function as an argument to box_read_*

### ISSUE THREAD

**Issue by tomsing1** [brendan-r/boxr#55]
Great package! I noticed that you provide functions to read different files directly, e.g. csv or excel files. Would it be useful to include a _generic_ function that allows the user to specify which R function to parse the file with?

For example, Mike Love's excellent [tximport function / package](https://github.com/mikelove/tximport/blob/master/R/tximport.R) includes the parser function, e.g. `read.csv` or `readr::read_delim`, as an argument. That way, the function is useful in many different contexts. At the same time, Mike didn't have to write multiple different functions for the various file formats.

Food for thought?
Best,
Thomas

**Comment by brendan-r** [comment]
Does the `read_fun` parameter in the function `box_read()` do what you want?

**Comment by tomsing1** [comment]
Yup, that's what I had in mind. Obviously, you are way ahead of me...

**Comment by dmgt** [comment]
I also really appreciate this package and have a similar question - does anyone have suggestions for existing examples of using `read_fun()` to use eg `box_read` with functions other than `data.table::fread` or `rio::import` ? 

My understanding is this is definitely possible, but have yet to get it working myself or find an example online, and since our team mostly uses `tidyverse`  it'd be really helpful to demonstrate reading files from BOX and using `readxl::read_excel` or `readr::read_csv`. 

I'd be grateful for any suggestions (and happy to help document this for folks with the same question in future).

**Comment by tomsing1** [comment]
@dmgt : Does the following examples help? You can pass any function to the `read_fun` argument of the `box_read` function you like. Or did I misunderstand you question?

```r
library(boxr)
library(readxl)
library(readr)
boxr::box_auth()

file_id <- "123456789"  # box id of an excel file
boxr::box_read_excel(file_id)
boxr::box_read(file_id, read_fun = readxl::read_excel)

file_id <- "987654321"  # box if of a csv file
boxr::box_read_csv(file_id)
boxr::box_read(file_id, read_fun = readr::read_csv)
```

**Comment by ijlyttle** [comment]
One of the things we are discussing is getting an enterprise developer account dedicated to this package. If that were the case, we could structure it so that we would have some sample files permanently availble, that we could use in runnable examples.
