### ISSUE TITLE
Error downloading file id ...: Client error: (403) Forbidden

### ISSUE THREAD

**Issue by mjafin** [brendan-r/boxr#64]
Hi there,
Thanks for a great package. I'm trying to use it to download files and have followed the instructions at https://cran.r-project.org/web/packages/boxr/vignettes/boxr.html although the UI now looks different from the instructions. I can list files so `box_ls()` works. However when I try to download files I'm getting a 403 Forbidden error. Any pointers how to resolve this? 

I'm using Box through my company subscription if that makes any difference at all.

Edit. I can `curl` download the files OK using the developer token

**Comment by mjafin** [comment]
Never mind, I ran `box_fresh_auth` and it helped.

**Comment by abhi5154** [comment]
Can you help me how you did it with box_fresh_auth?
Thanks in Advance.

**Comment by mjafin** [comment]
Hi @abhi5154, Just refreshed the process and ran it through. 

Further, it seems like in the Application Scopes of the app, the option "Read and write all files and folders stored in Box" needs to be selected even if you only intend to read data. 

That said, I haven't used this in some 3-4 months now and when I tried it yesterday it didn't work. Maybe things have changed again or my keys have expired (or something else).

**Comment by schourtney** [comment]
I'm having the exact same problem now :(

**Comment by stgran** [comment]
@schourtney I was actually just having the same problem and came here for the solution but just got it working. I've included my error at the bottom of this post.

I'm using RStudio and the line that was giving me problems was ```df <- boxr::box_read_csv(<my file id>)```. I had already successfully authenticated my Box account in RStudio.

It turns out that what I needed to do was, like @mjafin said, change the Application Scopes in my Box Developer app to include both "Read all files and folders stored in Box" and also "Write all files and folders stored in Box".

However, I still got the same error UNTIL I restarted my Box session and re-authenticated. I did this using ```boxr::box_fresh_auth()```, which prompted me to log back into Box each time, instead of ```boxr::box_auth()```. Voila! It worked for me after that.

Hope this helps.

The original error:
```
boxr: Authenticated using OAuth2 as <my name> (<my email>, id: <my id>)
Error in boxGet(file_id, local_file = temp_file, version_id = version_id,  : 
  Error downloading file id <my file id>: Client error: (403) Forbidden
```

**Comment by spencerkrichevsky** [comment]
I'm coming across the same error message now.

> However, I still got the same error UNTIL I restarted my Box session and re-authenticated. I did this using `boxr::box_fresh_auth()`, which prompted me to log back into Box (and will each time you run it), instead of `boxr::box_auth()`. 

I tried the above but caught the following error.

```
boxr::box_fresh_auth()
Error: `cache` must be a valid filename
```

Does anyone know what the cache file refers to? I'm also able to test alternative approaches that have worked for others. 

Boxr version:
```
packageVersion("boxr")
[1] ‘0.3.6’
```
